on:
  push:
    branches:
      -master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  windows_hello:
    runs-on: windows-latest
    steps:
      - run: echo "Hello World from Ubuntu Runner!!"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "GitHub Repository URL is ${{ github.repositoryUrl}} and branch is ${{ github.ref_name }} "
      - name: Cloning GitHub Repo 
        uses: actions/checkout@v3
      - name: List files in workspace using github.workspace found in my context
        run: ls ${{ github.workspace }}